=== apache/portals-pluto/pluto-portal-driver/src/main/resources/pluto-portal-driver-config.xsd
<?xml version="1.0"?>
<!--
   Copyright 2005-2006 The Apache Software Foundation
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
   
   http://www.apache.org/licenses/LICENSE-2.0
   
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:page="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd"
   targetNamespace="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd"
   elementFormDefault="qualified">

   <xs:complexType name="pageResourceRef">
      <xs:annotation>
         <xs:documentation>
         identification information for a page resource.
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="name" type="xs:token"/>
         <xs:element name="scope" type="xs:token" minOccurs="0" maxOccurs="1"/>
         <xs:element name="version" type="xs:token" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="pageResourceDefinition">
      <xs:annotation>
         <xs:documentation>
         Specifies a resource on which a portlet can depend. When a portlet depends on a
         page resource, the portal must place the resource on the page. The 'type' attribute
         on the 'source' tag designates the type of content. If the type is 'css' or 'script'
         the contents of the 'source' tag is taken to be a file specification relative to
         the pluto webapp base. If the type is 'markup', the contents of the tag is taken 
         character markup to be inserted into the document head section directly. 
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="identifier" type="page:pageResourceRef"/>
         <xs:element name="source">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:extension base="xs:string">
                     <xs:attribute name="type">
                        <xs:simpleType>
                           <xs:restriction base="xs:string">
                              <xs:enumeration value="script"/>
                              <xs:enumeration value="css"/>
                              <xs:enumeration value="markup"/>
                           </xs:restriction>
                        </xs:simpleType>
                     </xs:attribute>
               </xs:extension>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="pluto-portal-driver">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="portal-name" type="xs:token"
               default="pluto-portal-driver" />
            <xs:element name="portal-version" type="xs:token" />
            <xs:element name="container-name" type="xs:token" />

            <xs:element name="supports">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="portlet-mode"
                        type="xs:token" minOccurs="1" maxOccurs="unbounded" />
                     <xs:element name="window-state"
                        type="xs:token" minOccurs="1" maxOccurs="unbounded" />
                  </xs:sequence>
               </xs:complexType>
            </xs:element>

            <xs:element name="portlet-app" minOccurs="0"
               maxOccurs="unbounded">
               <xs:complexType>

                  <xs:sequence>
                     <xs:element name="context-path">
                        <xs:simpleType>
                           <xs:restriction base="xs:string">
                              <xs:pattern
                                 value="/[a-zA-Z0-9_ /]*" />
                           </xs:restriction>
                        </xs:simpleType>
                     </xs:element>

                     <xs:element name="portlets">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="portlet"
                                 minOccurs="1" maxOccurs="unbounded">
                                 <xs:complexType>
                                    <xs:attribute
                                       name="name" type="xs:token" />
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>

                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            
            <xs:element name="page-resources" minOccurs="0" maxOccurs="1">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="page-resource" type="page:pageResourceDefinition" minOccurs="1" maxOccurs="unbounded"/>
                     <xs:element name="default-resource" type="page:pageResourceRef" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>

            <xs:element name="render-config">
               <xs:complexType>

                  <xs:sequence>
                     <xs:element name="page" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="dependency" type="page:pageResourceRef" minOccurs="0" maxOccurs="unbounded"/>
                              <xs:element name="portlet" minOccurs="1" maxOccurs="unbounded">
                                 <xs:complexType>
                                    <xs:attribute name="context" type="xs:token" />
                                    <xs:attribute name="name" type="xs:token" />
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                           <xs:attribute name="name" type="xs:token" />
                           <xs:attribute name="uri" type="xs:token" />
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="default" type="xs:token" />
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== apache/portals-pluto/portlet-tck_3.0/V3PortletParametersTests/src/main/resources/xml-resources/additionalPages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.     
-->
<pluto-portal-driver xmlns="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd" xmlns:pa="http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd                         http://portals.apache.org/pluto/pluto-portal/1.1/pluto-portal-driver-config.xsd" version="1.1">
<portal-name>pluto-portal-driver</portal-name>
<portal-version>${project.version}</portal-version>
<container-name>Pluto Portal Driver</container-name>
<supports>
<portlet-mode>view</portlet-mode>
<portlet-mode>edit</portlet-mode>
<portlet-mode>help</portlet-mode>
<portlet-mode>config</portlet-mode>
<window-state>normal</window-state>
<window-state>maximized</window-state>
<window-state>minimized</window-state>
</supports>
<render-config default="About Apache Pluto">
<page xmlns="" name="V3PortletParametersTests" uri="/WEB-INF/themes/pluto-default-theme.jsp">
    <portlet context="/${project.artifactId}-${project.version}" name="PortletParametersTests_SPEC11_1"/>
</page>
<page xmlns="" name="V3ActionParametersTests" uri="/WEB-INF/themes/pluto-default-theme.jsp">
    <portlet context="/${project.artifactId}-${project.version}" name="PortletParametersTests_SPEC11_3"/>
</page>
<page xmlns="" name="V3ResourceParametersTests" uri="/WEB-INF/themes/pluto-default-theme.jsp">
    <portlet context="/${project.artifactId}-${project.version}" name="PortletParametersTests_SPEC11_4"/>
</page>
<page xmlns="" name="V3ResourceParametersAddlTests" uri="/WEB-INF/themes/pluto-default-theme.jsp">
    <portlet context="/${project.artifactId}-${project.version}" name="PortletParametersTests_SPEC11_4A"/>
</page>
</render-config>
</pluto-portal-driver>

=== apache/portals-pluto/portlet-tck_3.0/generated-resources/xml/module/tck-V3AnnotationPortletAppConfigOverrideTests-pages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.     
-->
<pluto-portal-driver xmlns="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd" xmlns:pa="http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd                         http://portals.apache.org/pluto/pluto-portal/1.1/pluto-portal-driver-config.xsd" version="1.1">
<portal-name>pluto-portal-driver</portal-name>
<portal-version>3.0-SNAPSHOT</portal-version>
<container-name>Pluto Portal Driver</container-name>
<supports>
<portlet-mode>view</portlet-mode>
<portlet-mode>edit</portlet-mode>
<portlet-mode>help</portlet-mode>
<portlet-mode>config</portlet-mode>
<window-state>normal</window-state>
<window-state>maximized</window-state>
<window-state>minimized</window-state>
</supports>
<render-config default="About Apache Pluto">
<page xmlns="" name="V3AnnotationPortletAppConfigOverrideTests" uri="/WEB-INF/themes/pluto-default-theme.jsp">
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_PortletModes"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_WindowStates"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_ResourceBundle"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_DefaultNamespaceURI"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_EventConfiguration1"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_EventConfiguration2"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_PublicRenderParameters1"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_PublicRenderParameters2"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_PublicRenderParameters3"/>
<portlet context="/tck-V3AnnotationPortletAppConfigOverrideTests-3.0-SNAPSHOT" name="AnnotationPortletAppConfigOverrideTests_SPEC1_28_PortletContainerRuntimeOptions"/>
</page>
</render-config>
</pluto-portal-driver>

=== apache/portals-pluto/pluto-portal-driver/src/main/resources/META-INF/pluto-portal-driver-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at 

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed  under the  License is distributed on an "AS IS" BASIS,
WITHOUT  WARRANTIES OR CONDITIONS  OF ANY KIND, either  express  or
implied.

See the License for the specific language governing permissions and
limitations under the License.
-->
<page:pluto-portal-driver xmlns:page="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portals.apache.org/pluto/xsd/pluto-portal-driver-config.xsd ../pluto-portal-driver-config.xsd ">
  <page:portal-name>pluto-portal-driver</page:portal-name>
  <page:portal-version>token</page:portal-version>
  <page:container-name>token</page:container-name>
  <page:supports>
    <page:portlet-mode>token</page:portlet-mode>
    <page:window-state>token</page:window-state>
  </page:supports>
  <page:portlet-app>
    <page:context-path>/dummypath</page:context-path>
    <page:portlets>
      <page:portlet name="token"/>
    </page:portlets>
  </page:portlet-app>
  <page:page-resources>
    <page:page-resource>
      <page:identifier>
        <page:name>token</page:name>
        <page:scope>token</page:scope>
        <page:version>token</page:version>
      </page:identifier>
      <page:source type="script">page:source</page:source>
    </page:page-resource>
    <page:default-resource>
      <page:name>token</page:name>
      <page:scope>token</page:scope>
      <page:version>token</page:version>
    </page:default-resource>
  </page:page-resources>
  <page:render-config default="token">
    <page:page name="token" uri="token">
      <page:dependency>
        <page:name>token</page:name>
        <page:scope>token</page:scope>
        <page:version>token</page:version>
      </page:dependency>
      <page:portlet context="token" name="token"/>
    </page:page>
  </page:render-config>
</page:pluto-portal-driver>
